### ISSUE TITLE
IntelliJ IDEA failures

### ISSUE THREAD

**Issue by Ravenwater** [SpinalHDL/SpinalTemplateSbt#1]
Trying to get started with the SpinalHDL using IntelliJ and I get this error:

Error while importing sbt project:

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Getting org.fusesource.jansi jansi 1.11 ...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/C:/Users/tomtz/.IntelliJIdea2017.3/config/plugins/Scala/launcher/sbt-launch.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.11/jansi-1.11.jar ...
[SUCCESSFUL ] org.fusesource.jansi#jansi;1.11!jansi.jar (219ms)
:: retrieving :: org.scala-sbt#boot-jansi
confs: [default]
1 artifacts copied, 0 already retrieved (111kB/62ms)
Getting org.scala-sbt sbt 0.13.16 ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.16/jars/sbt.jar ...
[SUCCESSFUL ] org.scala-sbt#sbt;0.13.16!sbt.jar (1288ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar ...
[SUCCESSFUL ] org.scala-lang#scala-library;2.10.6!scala-library.jar (1530ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.16/jars/main.jar ...
[SUCCESSFUL ] org.scala-sbt#main;0.13.16!main.jar (4229ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.16/jars/compiler-interface.jar ...
[SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.16!compiler-interface.jar (2037ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.16/jars/actions.jar ...
[SUCCESSFUL ] org.scala-sbt#actions;0.13.16!actions.jar (2736ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.16/jars/main-settings.jar ...
[SUCCESSFUL ] org.scala-sbt#main-settings;0.13.16!main-settings.jar (2499ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.16/jars/interface.jar ...
[SUCCESSFUL ] org.scala-sbt#interface;0.13.16!interface.jar (2031ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.16/jars/io.jar ...
[SUCCESSFUL ] org.scala-sbt#io;0.13.16!io.jar (2646ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.16/jars/ivy.jar ...
[SUCCESSFUL ] org.scala-sbt#ivy;0.13.16!ivy.jar (3468ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.16/jars/logging.jar ...
[SUCCESSFUL ] org.scala-sbt#logging;0.13.16!logging.jar (2295ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.16/jars/logic.jar ...
[SUCCESSFUL ] org.scala-sbt#logic;0.13.16!logic.jar (2109ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.16/jars/process.jar ...
[SUCCESSFUL ] org.scala-sbt#process;0.13.16!process.jar (1955ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.16/jars/run.jar ...
[SUCCESSFUL ] org.scala-sbt#run;0.13.16!run.jar (1898ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.16/jars/command.jar ...
[SUCCESSFUL ] org.scala-sbt#command;0.13.16!command.jar (2511ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar ...
[SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.1!launcher-interface.jar (224ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.16/jars/classpath.jar ...
[SUCCESSFUL ] org.scala-sbt#classpath;0.13.16!classpath.jar (1931ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.16/jars/completion.jar ...
[SUCCESSFUL ] org.scala-sbt#completion;0.13.16!completion.jar (2389ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.16/jars/api.jar ...
[SUCCESSFUL ] org.scala-sbt#api;0.13.16!api.jar (2270ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.16/jars/compiler-integration.jar ...
[SUCCESSFUL ] org.scala-sbt#compiler-integration;0.13.16!compiler-integration.jar (2012ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.16/jars/compiler-ivy-integration.jar ...
[SUCCESSFUL ] org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar (1789ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.16/jars/relation.jar ...
[SUCCESSFUL ] org.scala-sbt#relation;0.13.16!relation.jar (1566ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.16/jars/task-system.jar ...
[SUCCESSFUL ] org.scala-sbt#task-system;0.13.16!task-system.jar (1941ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.16/jars/tasks.jar ...
[SUCCESSFUL ] org.scala-sbt#tasks;0.13.16!tasks.jar (1805ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.16/jars/tracking.jar ...
[SUCCESSFUL ] org.scala-sbt#tracking;0.13.16!tracking.jar (1801ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.16/jars/testing.jar ...
[SUCCESSFUL ] org.scala-sbt#testing;0.13.16!testing.jar (1572ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.jar ...
[SUCCESSFUL ] org.scala-lang#scala-compiler;2.10.6!scala-compiler.jar (2357ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.jar ...
[SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.6!scala-reflect.jar (585ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.16/jars/control.jar ...
[SUCCESSFUL ] org.scala-sbt#control;0.13.16!control.jar (1880ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.16/jars/collections.jar ...
[SUCCESSFUL ] org.scala-sbt#collections;0.13.16!collections.jar (2498ms)
downloading https://repo1.maven.org/maven2/jline/jline/2.14.4/jline-2.14.4.jar ...
[SUCCESSFUL ] jline#jline;2.14.4!jline.jar (156ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.16/jars/classfile.jar ...
[SUCCESSFUL ] org.scala-sbt#classfile;0.13.16!classfile.jar (1835ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.16/jars/incremental-compiler.jar ...
[SUCCESSFUL ] org.scala-sbt#incremental-compiler;0.13.16!incremental-compiler.jar (2332ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.16/jars/compile.jar ...
[SUCCESSFUL ] org.scala-sbt#compile;0.13.16!compile.jar (2071ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.16/jars/persist.jar ...
[SUCCESSFUL ] org.scala-sbt#persist;0.13.16!persist.jar (1878ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar ...
[SUCCESSFUL ] org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar (1829ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.16/jars/cross.jar ...
[SUCCESSFUL ] org.scala-sbt#cross;0.13.16!cross.jar (1581ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar ...
[SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4!ivy.jar (566ms)
downloading https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar ...
[SUCCESSFUL ] com.jcraft#jsch;0.1.50!jsch.jar (172ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar ...
[SUCCESSFUL ] org.scala-sbt#serialization_2.10;0.1.2!serialization_2.10.jar (172ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar ...
[SUCCESSFUL ] org.scala-lang.modules#scala-pickling_2.10;0.10.1!scala-pickling_2.10.jar (247ms)
downloading https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar ...
[SUCCESSFUL ] org.json4s#json4s-core_2.10;3.2.10!json4s-core_2.10.jar (219ms)
downloading https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar ...
[SUCCESSFUL ] org.spire-math#jawn-parser_2.10;0.6.0!jawn-parser_2.10.jar (131ms)
downloading https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar ...
[SUCCESSFUL ] org.spire-math#json4s-support_2.10;0.6.0!json4s-support_2.10.jar (163ms)
downloading https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar ...
[SUCCESSFUL ] org.scalamacros#quasiquotes_2.10;2.0.1!quasiquotes_2.10.jar (230ms)
downloading https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar ...
[SUCCESSFUL ] org.json4s#json4s-ast_2.10;3.2.10!json4s-ast_2.10.jar (136ms)
downloading https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar ...
[SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.6!paranamer.jar (125ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.16/jars/cache.jar ...
[SUCCESSFUL ] org.scala-sbt#cache;0.13.16!cache.jar (1631ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.16/jars/test-agent.jar ...
[SUCCESSFUL ] org.scala-sbt#test-agent;0.13.16!test-agent.jar (1520ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar ...
[SUCCESSFUL ] org.scala-sbt#test-interface;1.0!test-interface.jar (135ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.16/jars/apply-macro.jar ...
[SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.16!apply-macro.jar (1560ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar ...
[SUCCESSFUL ] org.scala-sbt#template-resolver;0.1!template-resolver.jar (129ms)
:: retrieving :: org.scala-sbt#boot-app
confs: [default]
49 artifacts copied, 0 already retrieved (17616kB/183ms)
Getting Scala 2.10.6 (for sbt)...
downloading https://repo1.maven.org/maven2/org/scala-lang/jline/2.10.6/jline-2.10.6.jar ...
[SUCCESSFUL ] org.scala-lang#jline;2.10.6!jline.jar (175ms)
downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.4/jansi-1.4.jar ...
[SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar (160ms)
:: retrieving :: org.scala-sbt#boot-scala
confs: [default]
5 artifacts copied, 0 already retrieved (24494kB/62ms)
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by C:\Users\tomtz\.sbt\boot\scala-2.10.6\lib\scala-library.jar(scala/package.class)
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by C:\Users\tomtz\.sbt\boot\scala-2.10.6\lib\scala-library.jar(scala/runtime/package.class)
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:99)
at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:102)
at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:264)
at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:264)
at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass$lzycompute(Definitions.scala:263)
at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass(Definitions.scala:263)
at scala.reflect.internal.Definitions$DefinitionsClass.specialPolyClass(Definitions.scala:1120)
at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass$lzycompute(Definitions.scala:407)
at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass(Definitions.scala:407)
at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1154)
at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
at sbt.compiler.Eval$$anon$1.<init>(Eval.scala:141)
at sbt.compiler.Eval.run$lzycompute$1(Eval.scala:141)
at sbt.compiler.Eval.run$1(Eval.scala:141)
at sbt.compiler.Eval.unlinkAll$1(Eval.scala:144)
at sbt.compiler.Eval.evalCommon(Eval.scala:153)
at sbt.compiler.Eval.eval(Eval.scala:96)
at sbt.EvaluateConfigurations$.evaluateDslEntry(EvaluateConfigurations.scala:177)
at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:117)
at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:115)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
at scala.collection.immutable.List.foreach(List.scala:318)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
at scala.collection.AbstractTraversable.map(Traversable.scala:105)
at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:115)
at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:775)
at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:781)
at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:780)
at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
at scala.collection.AbstractMap.getOrElse(Map.scala:58)
at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:780)
at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
at scala.collection.AbstractTraversable.map(Traversable.scala:105)
at sbt.Load$.loadFiles$1(Load.scala:788)
at sbt.Load$.discoverProjects(Load.scala:799)
at sbt.Load$.discover$1(Load.scala:585)
at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:633)
at sbt.Load$$anonfun$loadUnit$1.sbt$Load$$anonfun$$loadProjects$1(Load.scala:482)
at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
at sbt.Load$.timed(Load.scala:1025)
at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:485)
at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
at sbt.Load$.timed(Load.scala:1025)
at sbt.Load$.loadUnit(Load.scala:459)
at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
at sbt.BuildLoader.apply(BuildLoader.scala:140)
at sbt.Load$.loadAll(Load.scala:365)
at sbt.Load$.loadURI(Load.scala:320)
at sbt.Load$.load(Load.scala:316)
at sbt.Load$.load(Load.scala:305)
at sbt.Load$$anonfun$4.apply(Load.scala:146)
at sbt.Load$$anonfun$4.apply(Load.scala:146)
at sbt.Load$.timed(Load.scala:1025)
at sbt.Load$.apply(Load.scala:146)
at sbt.Load$.buildPluginDefinition(Load.scala:886)
at sbt.Load$.buildPlugins(Load.scala:852)
at sbt.Load$.plugins(Load.scala:840)
at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
at sbt.Load$.timed(Load.scala:1025)
at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:464)
at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
at sbt.Load$.timed(Load.scala:1025)
at sbt.Load$.loadUnit(Load.scala:459)
at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
at sbt.BuildLoader.apply(BuildLoader.scala:140)
at sbt.Load$.loadAll(Load.scala:365)
at sbt.Load$.loadURI(Load.scala:320)
at sbt.Load$.load(Load.scala:316)
at sbt.Load$.load(Load.scala:305)
at sbt.Load$$anonfun$4.apply(Load.scala:146)
at sbt.Load$$anonfun$4.apply(Load.scala:146)
at sbt.Load$.timed(Load.scala:1025)
at sbt.Load$.apply(Load.scala:146)
at sbt.Load$.defaultLoad(Load.scala:39)
at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:503)
at sbt.BuiltinCommands$.doLoadProject(Main.scala:503)
at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
at sbt.Command$.process(Command.scala:93)
at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
at sbt.State$$anon$1.runCmd$1(State.scala:183)
at sbt.State$$anon$1.process(State.scala:187)
at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
at sbt.MainLoop$.next(MainLoop.scala:96)
at sbt.MainLoop$.run(MainLoop.scala:89)
at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
at sbt.Using.apply(Using.scala:24)
at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
at sbt.MainLoop$.runLogged(MainLoop.scala:22)
at sbt.StandardMain$.runManaged(Main.scala:61)
at sbt.xMain.run(Main.scala:35)
at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
at xsbt.boot.Launch$.run(Launch.scala:109)
at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
at xsbt.boot.Launch$.launch(Launch.scala:117)
at xsbt.boot.Launch$.apply(Launch.scala:18)
at xsbt.boot.Boot$.runImpl(Boot.scala:41)
at xsbt.boot.Boot$.main(Boot.scala:17)
at xsbt.boot.Boot.main(Boot.scala)
[error] scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[error] Use 'last' for the full log.
Invalid response.

Haven't done anything with Scala yet so starting pains as I have no idea what all of this means.

Please advise.

**Comment by Dolu1990** [comment]
Hi,

It is possible that you are using a java/javac 7 ?
If yes, could you try to update to java 8 ?

On debian => 

```
sudo add-apt-repository -y ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jdk -y
sudo update-alternatives --config java
sudo update-alternatives --config javac
```

update-alternatives will ask you to select the jvm, select the 1.8 ones ^^ (1.8 or 8)

**Comment by Ravenwater** [comment]
I am using JDK 10 on Windows, with IntelliJ 2017.3.5 Ultimate.

it appears that this is an IntelliJ problem: I see other folks reporting problems with the Scala plugin on IntelliJ.

**Comment by Dolu1990** [comment]
Hoo JDK 10 is out ?
So, to identify to issue more closely, you can use SBT as a commande line build script (a bit like makefile).

Just go in the root folder of the scala project with a terminal, and type        "sbt compile" If this fail, the issue isn't realy intellij.
I would say, try with Java/JDK 8. I already had issue with JDK 9, so with JDK 10 I realy have no idea how well it go :)

Let's me know how things go.

**Comment by Ravenwater** [comment]
That seems to work like a charm......

tomtz@SW-LAPTOP-250 MINGW64 /C/Users/tomtz/Documents/dev/SpinalTemplateSbt (mast                                                                                           er)
$ sbt compile
Copying runtime jar.
[info] Loading project definition from C:\Users\tomtz\Documents\dev\SpinalTemplateSbt\project
[info] Updating {file:/C:/Users/tomtz/Documents/dev/SpinalTemplateSbt/project/}spinaltemplatesbt-build...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/C:/Users/tomtz/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.16/ivy-0.13.16.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.10/sbt_0.13/5.2.1/jars/sbteclipse-plugin.jar ...
[info]  [SUCCESSFUL ] com.typesafe.sbteclipse#sbteclipse-plugin;5.2.1!sbteclipse-plugin.jar (2050ms)
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.10/7.2.14/scalaz-core_2.10-7.2.14.jar ...
[info]  [SUCCESSFUL ] org.scalaz#scalaz-core_2.10;7.2.14!scalaz-core_2.10.jar(bundle) (1830ms)
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-effect_2.10/7.2.14/scalaz-effect_2.10-7.2.14.jar ...
[info]  [SUCCESSFUL ] org.scalaz#scalaz-effect_2.10;7.2.14!scalaz-effect_2.10.jar(bundle) (178ms)
[info] Done updating.
[info] Set current project to SpinalTemplateSbt (in build file:/C:/Users/tomtz/Documents/dev/SpinalTemplateSbt/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Updating {file:/C:/Users/tomtz/Documents/dev/SpinalTemplateSbt/}spinaltemplatesbt...
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-library;2.11.6!scala-library.jar (889ms)
[info] downloading https://repo1.maven.org/maven2/com/github/spinalhdl/spinalhdl-core_2.11/1.1.3/spinalhdl-core_2.11-1.1.3.jar ...
[info]  [SUCCESSFUL ] com.github.spinalhdl#spinalhdl-core_2.11;1.1.3!spinalhdl-core_2.11.jar (454ms)
[info] downloading https://repo1.maven.org/maven2/com/github/spinalhdl/spinalhdl-lib_2.11/1.1.3/spinalhdl-lib_2.11-1.1.3.jar ...
[info]  [SUCCESSFUL ] com.github.spinalhdl#spinalhdl-lib_2.11;1.1.3!spinalhdl-lib_2.11.jar (826ms)
[info] downloading https://repo1.maven.org/maven2/com/github/spinalhdl/spinalhdl-sim_2.11/1.1.3/spinalhdl-sim_2.11-1.1.3.jar ...
[info]  [SUCCESSFUL ] com.github.spinalhdl#spinalhdl-sim_2.11;1.1.3!spinalhdl-sim_2.11.jar (137ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.plugins#scala-continuations-library_2.11;1.0.2!scala-continuations-library_2.11.jar(bundle) (131ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.6/scala-reflect-2.11.6.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.6!scala-reflect.jar (723ms)
[info] downloading https://repo1.maven.org/maven2/com/github/scopt/scopt_2.11/3.4.0/scopt_2.11-3.4.0.jar ...
[info]  [SUCCESSFUL ] com.github.scopt#scopt_2.11;3.4.0!scopt_2.11.jar (148ms)
[info] downloading https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar ...
[info]  [SUCCESSFUL ] commons-io#commons-io;2.4!commons-io.jar (139ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.6/1.0.2/scala-continuations-plugin_2.11.6-1.0.2.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.plugins#scala-continuations-plugin_2.11.6;1.0.2!scala-continuations-plugin_2.11.6.jar(bundle) (153ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.6/scala-compiler-2.11.6.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-compiler;2.11.6!scala-compiler.jar (2084ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.3/scala-xml_2.11-1.0.3.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.modules#scala-xml_2.11;1.0.3!scala-xml_2.11.jar(bundle) (206ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.3/scala-parser-combinators_2.11-1.0.3.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.modules#scala-parser-combinators_2.11;1.0.3!scala-parser-combinators_2.11.jar(bundle) (172ms)
[info] downloading https://repo1.maven.org/maven2/jline/jline/2.12.1/jline-2.12.1.jar ...
[info]  [SUCCESSFUL ] jline#jline;2.12.1!jline.jar (145ms)
[info] Done updating.
[info] Compiling 2 Scala sources to C:\Users\tomtz\Documents\dev\SpinalTemplateSbt\target\scala-2.11\classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.6. Compiling...
[info]   Compilation completed in 11.084 s
[success] Total time: 26 s, completed Mar 23, 2018, 5:40:09 PM

**Comment by Dolu1990** [comment]
Hooo any way you don't need mingw to run Spinal stuff :)

Hoo i'm sorry, you said "without a Scala SDK in module". Have you checked file/project structure ?

mine is : 
![image](https://user-images.githubusercontent.com/4832082/37854880-14cb87d8-2eed-11e8-94bb-ad4236a589dc.png)
