### ISSUE TITLE
sbt run fails 

### ISSUE THREAD

**Issue by darkstar007** [SpinalHDL/SpinalTemplateSbt#3]
Hi,

I'm on debian unstable, if I install scala and have sbt installed from the suggested repository, I get the follow issue:

```
git clone https://github.com/SpinalHDL/SpinalTemplateSbt.git
Cloning into 'SpinalTemplateSbt'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 182 (delta 0), reused 1 (delta 0), pack-reused 179
Receiving objects: 100% (182/182), 19.30 KiB | 6.43 MiB/s, done.
Resolving deltas: 100% (80/80), done.

cd SpinalTemplateSbt/

sbt run
Getting org.scala-sbt sbt 0.13.16  (this may take some time)...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.16/jars/sbt.jar ...
        [SUCCESSFUL ] org.scala-sbt#sbt;0.13.16!sbt.jar (1698ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-library;2.10.6!scala-library.jar (1465ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.16/jars/main.jar ...
        [SUCCESSFUL ] org.scala-sbt#main;0.13.16!main.jar (2438ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.16/jars/compiler-interface.jar ...
        [SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.16!compiler-interface.jar (1758ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.16/jars/actions.jar ...
        [SUCCESSFUL ] org.scala-sbt#actions;0.13.16!actions.jar (1793ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.16/jars/main-settings.jar ...
        [SUCCESSFUL ] org.scala-sbt#main-settings;0.13.16!main-settings.jar (1806ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.16/jars/interface.jar ...
        [SUCCESSFUL ] org.scala-sbt#interface;0.13.16!interface.jar (2516ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.16/jars/io.jar ...
        [SUCCESSFUL ] org.scala-sbt#io;0.13.16!io.jar (1755ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.16/jars/ivy.jar ...
        [SUCCESSFUL ] org.scala-sbt#ivy;0.13.16!ivy.jar (2093ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.16/jars/logging.jar ...
        [SUCCESSFUL ] org.scala-sbt#logging;0.13.16!logging.jar (1738ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.16/jars/logic.jar ...
        [SUCCESSFUL ] org.scala-sbt#logic;0.13.16!logic.jar (3086ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.16/jars/process.jar ...
        [SUCCESSFUL ] org.scala-sbt#process;0.13.16!process.jar (1693ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.16/jars/run.jar ...
        [SUCCESSFUL ] org.scala-sbt#run;0.13.16!run.jar (1790ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.16/jars/command.jar ...
        [SUCCESSFUL ] org.scala-sbt#command;0.13.16!command.jar (2018ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.1!launcher-interface.jar (108ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.16/jars/classpath.jar ...
        [SUCCESSFUL ] org.scala-sbt#classpath;0.13.16!classpath.jar (1693ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.16/jars/completion.jar ...
        [SUCCESSFUL ] org.scala-sbt#completion;0.13.16!completion.jar (1745ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.16/jars/api.jar ...
        [SUCCESSFUL ] org.scala-sbt#api;0.13.16!api.jar (1909ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.16/jars/compiler-integration.jar ...
        [SUCCESSFUL ] org.scala-sbt#compiler-integration;0.13.16!compiler-integration.jar (1722ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.16/jars/compiler-ivy-integration.jar ...
        [SUCCESSFUL ] org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar (1763ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.16/jars/relation.jar ...
        [SUCCESSFUL ] org.scala-sbt#relation;0.13.16!relation.jar (1739ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.16/jars/task-system.jar ...
        [SUCCESSFUL ] org.scala-sbt#task-system;0.13.16!task-system.jar (1760ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.16/jars/tasks.jar ...
        [SUCCESSFUL ] org.scala-sbt#tasks;0.13.16!tasks.jar (1691ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.16/jars/tracking.jar ...
        [SUCCESSFUL ] org.scala-sbt#tracking;0.13.16!tracking.jar (1692ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.16/jars/testing.jar ...
        [SUCCESSFUL ] org.scala-sbt#testing;0.13.16!testing.jar (2738ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-compiler;2.10.6!scala-compiler.jar (3239ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.6!scala-reflect.jar (692ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.16/jars/control.jar ...
        [SUCCESSFUL ] org.scala-sbt#control;0.13.16!control.jar (1724ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.16/jars/collections.jar ...
        [SUCCESSFUL ] org.scala-sbt#collections;0.13.16!collections.jar (2002ms)
downloading https://repo1.maven.org/maven2/jline/jline/2.14.4/jline-2.14.4.jar ...
        [SUCCESSFUL ] jline#jline;2.14.4!jline.jar (99ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.16/jars/classfile.jar ...
        [SUCCESSFUL ] org.scala-sbt#classfile;0.13.16!classfile.jar (1694ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.16/jars/incremental-compiler.jar ...
        [SUCCESSFUL ] org.scala-sbt#incremental-compiler;0.13.16!incremental-compiler.jar (1810ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.16/jars/compile.jar ...
        [SUCCESSFUL ] org.scala-sbt#compile;0.13.16!compile.jar (1733ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.16/jars/persist.jar ...
        [SUCCESSFUL ] org.scala-sbt#persist;0.13.16!persist.jar (1840ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar ...
        [SUCCESSFUL ] org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar (1674ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.16/jars/cross.jar ...
        [SUCCESSFUL ] org.scala-sbt#cross;0.13.16!cross.jar (1656ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar ...
        [SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4!ivy.jar (328ms)
downloading https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar ...
        [SUCCESSFUL ] com.jcraft#jsch;0.1.50!jsch.jar (97ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#serialization_2.10;0.1.2!serialization_2.10.jar (113ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar ...
        [SUCCESSFUL ] org.scala-lang.modules#scala-pickling_2.10;0.10.1!scala-pickling_2.10.jar (210ms)
downloading https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar ...
        [SUCCESSFUL ] org.json4s#json4s-core_2.10;3.2.10!json4s-core_2.10.jar (162ms)
downloading https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar ...
        [SUCCESSFUL ] org.spire-math#jawn-parser_2.10;0.6.0!jawn-parser_2.10.jar (64ms)
downloading https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar ...
        [SUCCESSFUL ] org.spire-math#json4s-support_2.10;0.6.0!json4s-support_2.10.jar (49ms)
downloading https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar ...
        [SUCCESSFUL ] org.scalamacros#quasiquotes_2.10;2.0.1!quasiquotes_2.10.jar (191ms)
downloading https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar ...
        [SUCCESSFUL ] org.json4s#json4s-ast_2.10;3.2.10!json4s-ast_2.10.jar (68ms)
downloading https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar ...
        [SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.6!paranamer.jar (66ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.16/jars/cache.jar ...
        [SUCCESSFUL ] org.scala-sbt#cache;0.13.16!cache.jar (1766ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.16/jars/test-agent.jar ...
        [SUCCESSFUL ] org.scala-sbt#test-agent;0.13.16!test-agent.jar (1687ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar ...
        [SUCCESSFUL ] org.scala-sbt#test-interface;1.0!test-interface.jar (49ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.16/jars/apply-macro.jar ...
        [SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.16!apply-macro.jar (1684ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#template-resolver;0.1!template-resolver.jar (46ms)
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        49 artifacts copied, 0 already retrieved (17616kB/59ms)
Getting Scala 2.10.6 (for sbt)...
downloading https://repo1.maven.org/maven2/org/scala-lang/jline/2.10.6/jline-2.10.6.jar ...
        [SUCCESSFUL ] org.scala-lang#jline;2.10.6!jline.jar (79ms)
downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.4/jansi-1.4.jar ...
        [SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar (67ms)
:: retrieving :: org.scala-sbt#boot-scala
        confs: [default]
        5 artifacts copied, 0 already retrieved (24494kB/39ms)
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /home/matt/.sbt/boot/scala-2.10.6/lib/scala-library.jar(scala/package.class)
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /home/matt/.sbt/boot/scala-2.10.6/lib/scala-library.jar(scala/runtime/package.class)
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
        at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
        at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
        at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:99)
        at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:102)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:264)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:264)
        at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass$lzycompute(Definitions.scala:263)
        at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass(Definitions.scala:263)
        at scala.reflect.internal.Definitions$DefinitionsClass.specialPolyClass(Definitions.scala:1120)
        at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass$lzycompute(Definitions.scala:407)
        at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass(Definitions.scala:407)
        at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1154)
        at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
        at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
        at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
       at sbt.compiler.Eval$$anon$1.<init>(Eval.scala:141)
        at sbt.compiler.Eval.run$lzycompute$1(Eval.scala:141)
        at sbt.compiler.Eval.run$1(Eval.scala:141)
        at sbt.compiler.Eval.unlinkAll$1(Eval.scala:144)
        at sbt.compiler.Eval.evalCommon(Eval.scala:153)
        at sbt.compiler.Eval.eval(Eval.scala:96)
        at sbt.EvaluateConfigurations$.evaluateDslEntry(EvaluateConfigurations.scala:177)
        at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:117)
        at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:115)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:115)
        at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:775)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:781)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:780)
        at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
        at scala.collection.AbstractMap.getOrElse(Map.scala:58)
        at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:780)
        at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
        at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Load$.loadFiles$1(Load.scala:788)
        at sbt.Load$.discoverProjects(Load.scala:799)
        at sbt.Load$.discover$1(Load.scala:585)
        at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:633)
        at sbt.Load$$anonfun$loadUnit$1.sbt$Load$$anonfun$$loadProjects$1(Load.scala:482)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:485)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.loadUnit(Load.scala:459)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
        at sbt.BuildLoader.apply(BuildLoader.scala:140)
        at sbt.Load$.loadAll(Load.scala:365)
        at sbt.Load$.loadURI(Load.scala:320)
        at sbt.Load$.load(Load.scala:316)
        at sbt.Load$.load(Load.scala:305)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.apply(Load.scala:146)
        at sbt.Load$.buildPluginDefinition(Load.scala:886)
        at sbt.Load$.buildPlugins(Load.scala:852)
        at sbt.Load$.plugins(Load.scala:840)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:464)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.loadUnit(Load.scala:459)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
        at sbt.BuildLoader.apply(BuildLoader.scala:140)
        at sbt.Load$.loadAll(Load.scala:365)
        at sbt.Load$.loadURI(Load.scala:320)
        at sbt.Load$.load(Load.scala:316)
        at sbt.Load$.load(Load.scala:305)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.apply(Load.scala:146)
        at sbt.Load$.defaultLoad(Load.scala:39)
        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:503)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:503)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.runCmd$1(State.scala:183)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.runCmd$1(State.scala:183)
        at sbt.State$$anon$1.process(State.scala:187)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:61)
        at sbt.xMain.run(Main.scala:35)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
[error] scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[error] Use 'last' for the full log.
```

I'm not sure where to start on how to identify what's gone wrong.

Thanks,

Matt

**Comment by Dolu1990** [comment]
Hi Matt,

Which version of java / javac is installated ?

If it is >= JDK9, / java 9, you need to go to java8 / JDK8

**Comment by darkstar007** [comment]
Hi,

OK, looks like I have 8, 9, 10 & 11 installed, and 11 used by default. 

If I re-run but do 
```
sbt -java-home /usr/lib/jvm/java-8-openjdk-amd64 run
```

Then it runs fine. Can I suggest an explicit note in the documentation and a runtime check would be cool?

Thanks,

Matt

**Comment by Dolu1990** [comment]
Thanks for the feedback, added the note in the readme.
Also you can set java8 as default with 

```sh
sudo update-alternatives --config java
sudo update-alternatives --config javac
```
