### ISSUE TITLE
when I update 1.7.0 to  1.8.0b ,the spinal.lib won't be pulled

### ISSUE THREAD

**Issue by Mido-sun** [SpinalHDL/SpinalTemplateSbt#32]
I just update my sbt.build from 1.7.0 to 1.8.0b  ,everything is normal except the spinal.lib ,it just disappear ！  I dont konw how to fix it

**Comment by Dolu1990** [comment]
I just tried, it's fine for me.
On sbt ?

maybe try a "sbt clean compile"

**Comment by Mido-sun** [comment]
I did it on IDEA . sbt the version under 1.7.0 are all ok   but 1.7.1 or higer  ,the spinal.lib wont pull

**Comment by Dolu1990** [comment]
So even in command line, "sbt clean compile" command isn't working ?

(Tryping to understand if that's a IDEA related issue, or SBT issue, it should first work on SBT before trying IDEA)

**Comment by Dolu1990** [comment]
You can go in the root folder of the repo, open a terminal, and run the command : 
sbt clean compile   
(in a single line)

**Comment by Mido-sun** [comment]
thank you  i tried  but still no spinal.lib   but when I use 1.7.0 and below version  it shows

**Comment by Mido-sun** [comment]
val spinalVersion = "1.8.0b"

scalaVersion := "2.11.12"

fork := true

libraryDependencies ++= Seq(

  "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.2",

  "com.github.spinalhdl" % "spinalhdl-core_2.11" % spinalVersion,

  "com.github.spinalhdl" % "spinalhdl-lib_2.11" % spinalVersion,

  compilerPlugin("com.github.spinalhdl" % "spinalhdl-idsl-plugin_2.11" % spinalVersion)

)


here is my build sbt

**Comment by Dolu1990** [comment]
can you zip me your project and send me the console logs when you run 
sbt clean compile ?

**Comment by Mido-sun** [comment]
sbt thinks that server is already booting because of this exception:
sbt.internal.ServerAlreadyBootingException: java.io.IOException: Could not create lock for \\.\pipe\sbt-load6894655030307012766_lock, error 5
        at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:356)
        at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:295)
        at sbt.xMain$.getSocketOrExit(Main.scala:150)
        at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:77)
        at sbt.xMain$.bootServerSocket$1(Main.scala:77)
        at sbt.xMain$.withStreams$1(Main.scala:85)
        at sbt.xMain$.run(Main.scala:121)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: Could not create lock for \\.\pipe\sbt-load6894655030307012766_lock, error 5
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:129)
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:48)
        at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:350)
        ... 21 more
Create a new server? y/n (default y)
[info] welcome to sbt 1.8.0 (Oracle Corporation Java 18.0.2)
[info] loading global plugins from D:\sbt\.sbt\plugins
[info] loading project definition from D:\scala project\demo1\project
[info] loading settings for project demo1 from build.sbt ...
[info] set current project to demo1 (in build file:/D:/scala%20project/demo1/)
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed 2023骞?鏈?鏃?涓婂崍9:36:48
[info] compiling 18 Scala sources to D:\scala project\demo1\target\scala-2.11\classes ...
[error] D:\scala project\demo1\src\main\scala\XG\compress.scala:5:15: object lib is not a member of package spinal
[error] import spinal.lib._
[error]               ^
[error] D:\scala project\demo1\src\main\scala\XG\compress.scala:10:22: not found: value slave
[error]         val dataIn = slave(Flow(SInt(inWidth bits)))

**Comment by Mido-sun** [comment]
the  project I am afraid that I can't upload for the rules of my company  sorry

**Comment by Mido-sun** [comment]
I  have tried use Offline jar ，but when I run the scala ,all the class cant be Identification

**Comment by Dolu1990** [comment]
Ahhh so that's realy a sbt / windows issue i think, can you try updating https://github.com/SpinalHDL/SpinalTemplateSbt/blob/master/project/build.properties to 1.8.2 ?

**Comment by Mido-sun** [comment]
emm  it seems not work for me

**Comment by Dolu1990** [comment]
So, would it be possible to share the project, with all the scala source and work specific things stripped away ?

**Comment by Mido-sun** [comment]
I use the offline spinal.lib and compile success . I don't know why it did not work before . Maybe IDEA trolling .
Thanks anyway ,but the online sbt pull still do not work . For the rules of my company  I can't upload anything to internet ,sorry .

**Comment by Dolu1990** [comment]
Maybe a few depedencies changed, so you would need to update your ivy2 cache ?

**Comment by Mido-sun** [comment]
﻿emm I don’t operate that .I can use the 1.8.0b now at least . the problem is that I  need to update manually when the next version update xd 在 2023年3月3日，17:38，Dolu1990 ***@***.***> 写道：﻿
Maybe a few depedencies changed, so you would need to update your ivy2 cache ?

**Comment by Dolu1990** [comment]
> Maybe IDEA trolling 

That's quite possible :)
