### ISSUE TITLE
sbt run fail "error: not found: value EclipseKeys"

### ISSUE THREAD

**Issue by aurabindo** [SpinalHDL/SpinalTemplateSbt#4]
I am running on Fedora 29, and Java 1.8 is the default. Full message:
```
[aj@fedaura SpinalTemplateSbt]$ sbt "run-main mylib.MyTopLevelVerilog"
[info] Loading project definition from /home/aj/learning/spinal_hdl/SpinalTemplateSbt/project
/home/aj/learning/spinal_hdl/SpinalTemplateSbt/build.sbt:7: error: not found: value EclipseKeys
EclipseKeys.withSource := true
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[error] Expected ID character
[error] Not a valid command: run-main
[error] run-main mylib.MyTopLevelVerilog
[error]         ^
```
What could be the reason for this failure ?

**Comment by Dolu1990** [comment]
Hmm that's weird, i just try on my setup, it work fine. As a work around, you can comment out this line : 
https://github.com/SpinalHDL/SpinalTemplateSbt/blob/master/build.sbt#L7

Should be fine then.
Let's me know if the issue is persistant :)

**Comment by aurabindo** [comment]
Quite weird indeed. Without that line, I get an error:
```
/home/aj/learning/spinal_hdl/SpinalTemplateSbt/build.sbt:13: error: eof expected but ';' found.
scalacOptions += "-P:continuations:enable"
^
[error] Error parsing expression.  Ensure that settings are separated by blank lines.
```

I added a newline after the offending line 13, and it gets past that error, and now I have a new error:

```
[info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-parser-combinators_2.11;1.0.3!scala-parser-combinators_2.11.jar(bundle) (3178ms)
[info] downloading https://repo1.maven.org/maven2/jline/jline/2.12.1/jline-2.12.1.jar ...
[info] 	[SUCCESSFUL ] jline#jline;2.12.1!jline.jar (2670ms)
[info] Done updating.
[info] Compiling 2 Scala sources to /home/aj/learning/spinal_hdl/SpinalTemplateSbt/target/scala-2.11/classes...
sbt.InvalidComponent: Could not find required component 'compiler-interface-src'
	at sbt.ComponentManager.invalid(ComponentManager.scala:57)
	at sbt.ComponentManager.sbt$ComponentManager$$notFound$1(ComponentManager.scala:34)
----
SNIP
----

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (compile:compile) sbt.InvalidComponent: Could not find required component 'compiler-interface-src'
[error] Total time: 132 s, completed Dec 15, 2018 10:12:12 PM
```
